### ISSUE TITLE
Repo codebase & initial config tasks

### ISSUE THREAD

**Issue by alewis729** [alewis729/expense-tracker#2]
## Tasks

- [x] Create monorepo codebase
- [x] Setup vercel ci/cd
- [x] Design fontend prototypes
